### ISSUE TITLE
Add robots meta tag and "nofollow" link attribute

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1346]
1. Fragile pages should be not indexed by search engines.
```
<meta name=”robots” content=”nofollow, noindex”>
```
- [x] Add above meta tag to order's confirmation page

2. Pages that brings no to little content value should not be crawled
```
<meta name=”robots” content=”nofollow”>
```
- [x] Add above meta tag to sign in/sign up/cart pages 
3.  Add link attribute
- [x] Links pointing to above pages should have set attribute `rel="nofollow"`
