### ISSUE TITLE
Refactor API client in tests

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3003]
Calling API in tests requires us to write some repetitive code:
```
admin_api_client.post(reverse('api'), {'query': query, 'variables': variables})
```

Both the URL and structure of the data dictionary are the same in every API, so we could adjust the `post` method of our `ApiClient` and have something like:
```
admin_api_client.post(query, variables)
```

We could also experiment with passing permissions to be used for a particular call, e.g.
```
admin_api_client.post(query, variables, permissions=[permission_manage_orders])
```

## TODO
- [x] New method `post_grapqhl` for simplified query posting
- [ ] All tests tested with `staff_api_client` instead of `admin_api_client`
- [ ] `admin_api_client` is removed
- [ ] API-related fixtures should be moved to `tests/api/conftest.py`

**Comment by Pacu2** [comment]
I'll handle it after merging #3002 and #2988 as it will create tons of conflicts

**Comment by Pacu2** [comment]
Also, GraphQL related set up should live in `tests/api/conftest.py`, instead of the regular one.

**Comment by maarcingebala** [comment]
We could also try to tackle the problem that we have now three clients: `admin_api_client`, `staff_api_client` and `user_api_client`. I don't know if `admin_api_client` that simulates a superuser is needed at all - we should rather always use the `staff_api_client` and test the proper permissions.

**Comment by Pacu2** [comment]
@maarcingebala I'd drop an admin_api_client to make the folks test the permission each time they're testing

**Comment by Pacu2** [comment]
My proposition is:

- Creating a new post_graphql method that will take 3 arguments: query, variables, and permissions
- If variables are provided, we will call `json.dumps` on them (one less thing to do in every test)
- This method will post to `/api/` by default
- If permissions are provided, we will post the query without permissions, assert no permission error, and post another time with permissions added
