### ISSUE TITLE
Add description field to collection model

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3134]
### What I'm trying to achieve
To add a description to a collection.

### Describe a proposed solution
Add `description` field to `Collection` model.

### TODO 
- [ ] Add description field to `Collection` model
- [ ] Add description field to `CollectionTranslation` model
- [ ] Adding migrations
- [ ] Add `description` to Collection's forms & templates in the dashboard
- [ ] Adding `description` field to Collection's GraphQL APIs (mutations and types)
- [ ] Adjust "SEO Widget" logic on the dashboard, on Collection Add/Edit page (description should be used as a placeholder if seo_description is missing)
- [ ] Adjust tests for all of the above

**Comment by pmutua** [comment]
# Detailed Explanation 

- adding migrations
- expanding forms in the dashboard
- adding this field to GraphQL APIs

**Comment by gagantrivedi** [comment]
can i take this up ?

**Comment by Pacu2** [comment]
@gagantrivedi go for it!
