### ISSUE TITLE
Use VerstaileImageField to generate Category/Collection thumbnails

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3266]
At this moment, `background_image` of Categories and Collections are available only in their original size. We should generate thumbnails (using `create_thumbnails` function) to keep them consistent no matter of the original size.

We could start with just one size(universal, for setting it as a background_image on category/collection page), that could be used as a base for an potential expansion in the future. 

## TODO:
- [ ] Generate `background_image` thubmanils on Category/Collection save (both via Dashboard forms and Dashboard 2.0 GraphQL queries)
- [ ] Define new key set in `VERSATILEIMAGEFIELD_RENDITION_KEY_SETS` specially for Categories and Collections
- [ ] Generate thumbnails for categories/collections created during the `populatedb` command
- [ ] Test all of the above
