### ISSUE TITLE
Unify the sorting logic

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4353]
We decided to adopt a new logic, sorting by relative order in #4123. With #4257 coming, #4123's logic will be extracted to abstract objects.

In #3958 we have implemented an absolute ordering.

In a few other places we also have absolute (or implicit?) ordering. We should unify the sorting logic all over the API. But it might break dashboard 1.0–it might be better if we do this after dropping it.

## Tasks
- [ ] Unify menu ordering -> `MenuItemMove`
- [x] ~~Unify product image ordering -> `ProductImageReorder`~~ not needed.
- [ ] Make sure the fields are no longer available through the API
- [ ] Make sure the resolvers always return the correct order
- [ ] Update dashboard 2.0

**Comment by NyanKiyoshi** [comment]
@maarcingebala I think it would be great to do it "ASAP", a.k.a. once we are almost ready for #4351. So we have a unified logic and don't expose ordering anymore.

It will break the dashboard 2.0, so we will need Dominik to help on it 👍
