### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#810]
Once 1.11 ships we should switch to supporting 1.11 as it's an LTS and possibly 1.8 if we want to give our users option of using an earlier LTS (still supported until 2018).

This is a tracking bug for 1.11 compatibility.

* [x] `django-countries`: SmileyChris/django-countries#164
* [x] `django-bootstrap3`
* [ ] `django-materializecss-form`: florent1933/django-materializecss-form#13
* [ ] `django-emailit`: divio/django-emailit#10

**Comment by patrys** [comment]
I propose that we drop both `django-materializecss-form` and `django-emailit`. Both are unresponsive and cannot be considered maintained well enough for us to depend on them.

The first one can easily be replaced with a couple of template tags inside Saleor.

The latter can be dropped in favor of [django-templated-email](https://github.com/vintasoftware/django-templated-email) and [django-anymail](https://github.com/anymail/django-anymail). One thing worth mentioning is that `django-emailit` calls `premailer` before sending each message. We should instead recommend inlining styles in the template itself, there's no reason to do it every time an email is sent.

**Comment by patrys** [comment]
https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/

**Comment by krzysztofwolski** [comment]
FYI: Since Saleor has templates folder in root directory, overwritten widget templates will have problems with finding files. Default form renderer search for templates in app directories
https://docs.djangoproject.com/en/1.11/ref/forms/renderers/#the-low-level-render-api

**Comment by patrys** [comment]
I really wish forms did not try to render themselves to HTML 😞
